# Default values for mop.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  registry:
  repository: mysql
  name: mysql-operator
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  pullSecrets:
    enabled: false
    secretName:
    registry:
    username:
    password:
    email: user@example.com

envs:
    imagesPullPolicy: IfNotPresent
    imagesDefaultRegistry: 
    imagesDefaultRepository:

# Unused
serviceAccount:
  annotations: {}

podAnnotations: {}

# Unused
podSecurityContext: {}

# Unused
securityContext: {}


# Unused
resources: {}

# Unused
nodeSelector: {}

# Unused
tolerations: []

# Unused
affinity: {}
