apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-operator-sa
  namespace: {{ if and (.Release.IsInstall) (eq .Release.Namespace "default") }}{{ fail "Please provide a namespace with -n/--namespace" }}{{ else }}{{  .Release.Namespace }}{{ end }}
{{- if .Values.image.pullSecrets.enabled }}
imagePullSecrets:
- name: {{ .Values.image.pullSecrets.secretName | default "priv-reg-secret" }}
{{- end }}